// App
exports.SET_USER_PROFILE = 'SET_USER_PROFILE'
exports.SET_USER = 'SET_USER'
exports.REDIRECT = 'REDIRECT'
exports.SET_URL = 'SET_URL'
exports.SIGN_OUT = 'SIGN_OUT'
exports.SAVE = 'SAVE'
exports.MENU = 'MENU'
exports.MODAL = 'MODAL'
exports.CLOSE_MODALS = 'CLOSE_MODALS'
exports.RESET = 'RESET'
exports.SET_NOTIFICATION = 'SET_NOTIFICATION'

// Editor
exports.OPEN_NEW = 'OPEN_NEW'
exports.CLOSE_NEW = 'CLOSE_NEW'

exports.NEW_ROW = 'NEW_ROW'
exports.DESTROY_ROW = 'DESTROY_ROW'

exports.NEW_COLUMN = 'NEW_COLUMN'
exports.RENAME_COLUMN = 'RENAME_COLUMN'
exports.DESTROY_COLUMN = 'DESTROY_COLUMN'

exports.DESTROY = 'DESTROY'

exports.SET_ACTIVE_ROW = 'SET_ACTIVE_ROW'
exports.SET_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY'
exports.PROPERTY_TYPE = 'PROPERTY_TYPE'
exports.UPDATE_ROW = 'UPDATE_ROW'

// Github
exports.SET_GITHUB_BRANCHES = 'SET_GITHUB_BRANCHES'
exports.SET_GITHUB_ORGS = 'SET_GITHUB_ORGS'
exports.SET_GITHUB_REPOS = 'SET_GITHUB_REPOS'
exports.SET_GITHUB_FILES = 'SET_GITHUB_FILES'

exports.CLEAR_ORGS = 'CLEAR_ORGS'
exports.CLEAR_REPOS = 'CLEAR_REPOS'
exports.CLEAR_BRANCHES = 'CLEAR_BRANCHES'

exports.SELECTED_BRANCH = 'SELECTED_BRANCH'
exports.SELECTED_FILE = 'SELECTED_FILE'
exports.SELECTED_REPO = 'SELECTED_REPO'
exports.SELECTED_ORG = 'SELECTED_ORG'

exports.SAVE_TO_GITHUB_SUCCESS = 'SAVE_TO_GITHUB_SUCCESS'

// File Ops
exports.SET_FILENAME = 'SET_FILENAME'
exports.SET_FILE_TYPE = 'SET_FILE_TYPE'
exports.SET_FILE = 'SET_FILE'
